# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_CicloSabathe.ui'
#
# Created: Sun May  1 00:42:53 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(719, 454)
        self.horizontalLayout_26 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.DatosEntrada = QtGui.QFrame(Dialog)
        self.DatosEntrada.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DatosEntrada.setFrameShadow(QtGui.QFrame.Raised)
        self.DatosEntrada.setObjectName("DatosEntrada")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.DatosEntrada)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtGui.QLabel(self.DatosEntrada)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_2 = QtGui.QLabel(self.DatosEntrada)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_19.addWidget(self.label_2)
        self.formula_comboBox = QtGui.QComboBox(self.DatosEntrada)
        self.formula_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.formula_comboBox.setObjectName("formula_comboBox")
        self.formula_comboBox.addItem("")
        self.horizontalLayout_19.addWidget(self.formula_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.formula_frame = QtGui.QFrame(self.DatosEntrada)
        self.formula_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.formula_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formula_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.formula_frame.setObjectName("formula_frame")
        self.label_5 = QtGui.QLabel(self.formula_frame)
        self.label_5.setGeometry(QtCore.QRect(80, 0, 13, 23))
        self.label_5.setObjectName("label_5")
        self.formulaO = QtGui.QLineEdit(self.formula_frame)
        self.formulaO.setGeometry(QtCore.QRect(90, 10, 21, 27))
        self.formulaO.setObjectName("formulaO")
        self.label_3 = QtGui.QLabel(self.formula_frame)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 12, 23))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtGui.QLabel(self.formula_frame)
        self.label_7.setGeometry(QtCore.QRect(110, 0, 11, 23))
        self.label_7.setObjectName("label_7")
        self.formulaC = QtGui.QLineEdit(self.formula_frame)
        self.formulaC.setGeometry(QtCore.QRect(30, 10, 21, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formulaC.sizePolicy().hasHeightForWidth())
        self.formulaC.setSizePolicy(sizePolicy)
        self.formulaC.setObjectName("formulaC")
        self.label_4 = QtGui.QLabel(self.formula_frame)
        self.label_4.setGeometry(QtCore.QRect(50, 0, 13, 23))
        self.label_4.setObjectName("label_4")
        self.formulaH = QtGui.QLineEdit(self.formula_frame)
        self.formulaH.setGeometry(QtCore.QRect(60, 10, 21, 27))
        self.formulaH.setObjectName("formulaH")
        self.widget = QtGui.QWidget(self.formula_frame)
        self.widget.setGeometry(QtCore.QRect(130, 0, 81, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formulaS = QtGui.QLineEdit(self.widget)
        self.formulaS.setObjectName("formulaS")
        self.horizontalLayout_6.addWidget(self.formulaS)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_4.addWidget(self.formula_frame)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_relacionMezcla = QtGui.QLabel(self.DatosEntrada)
        self.label_relacionMezcla.setAlignment(QtCore.Qt.AlignCenter)
        self.label_relacionMezcla.setObjectName("label_relacionMezcla")
        self.horizontalLayout.addWidget(self.label_relacionMezcla)
        self.relacionMezcla = QtGui.QDoubleSpinBox(self.DatosEntrada)
        self.relacionMezcla.setMaximum(2.0)
        self.relacionMezcla.setSingleStep(0.01)
        self.relacionMezcla.setProperty("value", 1.0)
        self.relacionMezcla.setObjectName("relacionMezcla")
        self.horizontalLayout.addWidget(self.relacionMezcla)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_HVS = QtGui.QLabel(self.DatosEntrada)
        self.label_HVS.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HVS.setObjectName("label_HVS")
        self.horizontalLayout_2.addWidget(self.label_HVS)
        self.HVS_lineEdit = QtGui.QLineEdit(self.DatosEntrada)
        self.HVS_lineEdit.setObjectName("HVS_lineEdit")
        self.horizontalLayout_2.addWidget(self.HVS_lineEdit)
        self.label_HVI = QtGui.QLabel(self.DatosEntrada)
        self.label_HVI.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HVI.setObjectName("label_HVI")
        self.horizontalLayout_2.addWidget(self.label_HVI)
        self.HVI_lineEdit = QtGui.QLineEdit(self.DatosEntrada)
        self.HVI_lineEdit.setObjectName("HVI_lineEdit")
        self.horizontalLayout_2.addWidget(self.HVI_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Q = QtGui.QLabel(self.DatosEntrada)
        self.label_Q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q.setObjectName("label_Q")
        self.horizontalLayout_3.addWidget(self.label_Q)
        self.calorQ = QtGui.QLineEdit(self.DatosEntrada)
        self.calorQ.setObjectName("calorQ")
        self.horizontalLayout_3.addWidget(self.calorQ)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtGui.QLabel(self.DatosEntrada)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtGui.QLabel(self.DatosEntrada)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.presion1 = QtGui.QLineEdit(self.DatosEntrada)
        self.presion1.setObjectName("presion1")
        self.horizontalLayout_4.addWidget(self.presion1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtGui.QLabel(self.DatosEntrada)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.temperatura1 = QtGui.QLineEdit(self.DatosEntrada)
        self.temperatura1.setObjectName("temperatura1")
        self.horizontalLayout_5.addWidget(self.temperatura1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_16.addLayout(self.verticalLayout)
        self.Altura_Button = QtGui.QPushButton(self.DatosEntrada)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Altura_Button.sizePolicy().hasHeightForWidth())
        self.Altura_Button.setSizePolicy(sizePolicy)
        self.Altura_Button.setObjectName("Altura_Button")
        self.horizontalLayout_16.addWidget(self.Altura_Button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtGui.QLabel(self.DatosEntrada)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.selecDatoExtra1 = QtGui.QComboBox(self.DatosEntrada)
        self.selecDatoExtra1.setObjectName("selecDatoExtra1")
        self.selecDatoExtra1.addItem("")
        self.selecDatoExtra1.addItem("")
        self.horizontalLayout_17.addWidget(self.selecDatoExtra1)
        self.datoExtra1 = QtGui.QLineEdit(self.DatosEntrada)
        self.datoExtra1.setObjectName("datoExtra1")
        self.horizontalLayout_17.addWidget(self.datoExtra1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.selecDatoExtra2 = QtGui.QComboBox(self.DatosEntrada)
        self.selecDatoExtra2.setObjectName("selecDatoExtra2")
        self.selecDatoExtra2.addItem("")
        self.selecDatoExtra2.addItem("")
        self.selecDatoExtra2.addItem("")
        self.selecDatoExtra2.addItem("")
        self.horizontalLayout_18.addWidget(self.selecDatoExtra2)
        self.datoExtra2 = QtGui.QLineEdit(self.DatosEntrada)
        self.datoExtra2.setObjectName("datoExtra2")
        self.horizontalLayout_18.addWidget(self.datoExtra2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.calcular = QtGui.QPushButton(self.DatosEntrada)
        self.calcular.setObjectName("calcular")
        self.verticalLayout_5.addWidget(self.calcular)
        self.horizontalLayout_26.addWidget(self.DatosEntrada)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.PlotArea = QtGui.QTabWidget(Dialog)
        self.PlotArea.setMovable(False)
        self.PlotArea.setObjectName("PlotArea")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.PlotArea.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.PlotArea.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.PlotArea)
        self.DatosSalida = QtGui.QFrame(Dialog)
        self.DatosSalida.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DatosSalida.setFrameShadow(QtGui.QFrame.Raised)
        self.DatosSalida.setObjectName("DatosSalida")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.DatosSalida)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtGui.QLabel(self.DatosSalida)
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtGui.QLabel(self.DatosSalida)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        self.calor2 = QtGui.QLineEdit(self.DatosSalida)
        self.calor2.setObjectName("calor2")
        self.horizontalLayout_20.addWidget(self.calor2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_19 = QtGui.QLabel(self.DatosSalida)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_21.addWidget(self.label_19)
        self.calorU = QtGui.QLineEdit(self.DatosSalida)
        self.calorU.setObjectName("calorU")
        self.horizontalLayout_21.addWidget(self.calorU)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_20 = QtGui.QLabel(self.DatosSalida)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_22.addWidget(self.label_20)
        self.trabajoW = QtGui.QLineEdit(self.DatosSalida)
        self.trabajoW.setObjectName("trabajoW")
        self.horizontalLayout_22.addWidget(self.trabajoW)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.matrixButton = QtGui.QPushButton(self.DatosSalida)
        self.matrixButton.setObjectName("matrixButton")
        self.verticalLayout_7.addWidget(self.matrixButton)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_21 = QtGui.QLabel(self.DatosSalida)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        self.presionMedia = QtGui.QLineEdit(self.DatosSalida)
        self.presionMedia.setObjectName("presionMedia")
        self.horizontalLayout_24.addWidget(self.presionMedia)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtGui.QLabel(self.DatosSalida)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.rendimiento = QtGui.QLineEdit(self.DatosSalida)
        self.rendimiento.setObjectName("rendimiento")
        self.horizontalLayout_23.addWidget(self.rendimiento)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_25.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.DatosSalida)
        self.horizontalLayout_26.addLayout(self.verticalLayout_8)

        self.retranslateUi(Dialog)
        self.PlotArea.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.formulaC, self.formulaH)
        Dialog.setTabOrder(self.formulaH, self.formulaO)
        Dialog.setTabOrder(self.formulaO, self.formulaS)
        Dialog.setTabOrder(self.formulaS, self.relacionMezcla)
        Dialog.setTabOrder(self.relacionMezcla, self.calorQ)
        Dialog.setTabOrder(self.calorQ, self.presion1)
        Dialog.setTabOrder(self.presion1, self.selecDatoExtra2)
        Dialog.setTabOrder(self.selecDatoExtra2, self.datoExtra2)
        Dialog.setTabOrder(self.datoExtra2, self.calor2)
        Dialog.setTabOrder(self.calor2, self.calorU)
        Dialog.setTabOrder(self.calorU, self.trabajoW)
        Dialog.setTabOrder(self.trabajoW, self.presionMedia)
        Dialog.setTabOrder(self.presionMedia, self.rendimiento)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Datos de Entrada</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Formula Química:", None, QtGui.QApplication.UnicodeUTF8))
        self.formula_comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Otra", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">O</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaO.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">C</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">+</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaC.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">H</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaH.setText(QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaS.setText(QtGui.QApplication.translate("Dialog", "00.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">% </span><span style=\" font-size:12pt; font-weight:600;\">S</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_relacionMezcla.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Relación de mezcla F<span style=\" vertical-align:sub;\">r </span>=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_HVS.setText(QtGui.QApplication.translate("Dialog", "HVS [KJ/kg]=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_HVI.setText(QtGui.QApplication.translate("Dialog", "HVI [KJ/kg]=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Q.setText(QtGui.QApplication.translate("Dialog", "Calor aportado [KJ/kg aire]=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Parametros atmosféricos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>P<span style=\" vertical-align:sub;\">1</span>  [Pa] =</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.presion1.setText(QtGui.QApplication.translate("Dialog", "101325", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">1</span>  [K] =</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatura1.setText(QtGui.QApplication.translate("Dialog", "293", None, QtGui.QApplication.UnicodeUTF8))
        self.Altura_Button.setText(QtGui.QApplication.translate("Dialog", "Selecionar Altura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Datos del ciclo:", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra1.setItemText(0, QtGui.QApplication.translate("Dialog", "Relacion de comp.    =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra1.setItemText(1, QtGui.QApplication.translate("Dialog", "T2                                =", None, QtGui.QApplication.UnicodeUTF8))
        self.datoExtra1.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(0, QtGui.QApplication.translate("Dialog", "Alpha                            =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(1, QtGui.QApplication.translate("Dialog", "Beta                              =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(2, QtGui.QApplication.translate("Dialog", "Presion max                =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(3, QtGui.QApplication.translate("Dialog", "Temp. max                  =", None, QtGui.QApplication.UnicodeUTF8))
        self.datoExtra2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.calcular.setText(QtGui.QApplication.translate("Dialog", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotArea.setTabText(self.PlotArea.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Diagrama P-V", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotArea.setTabText(self.PlotArea.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Diagrama T-S (Mollier)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Datos de Salida</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Q<span style=\" vertical-align:sub;\">2 </span>[KJ/kg aire]=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Qu<span style=\" vertical-align:sub;\"/>[KJ/kg aire]=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>W[KJ/kg aire]=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matrixButton.setText(QtGui.QApplication.translate("Dialog", "Matriz de Resultados", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Presión media [Pa]=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Rendimiento [KJ/kg aire]=", None, QtGui.QApplication.UnicodeUTF8))

