# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CicloSabatheGUI_V02.ui'
#
# Created: Sun Apr 05 03:22:25 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(688, 399)
        self.DatosEntrada = QtGui.QFrame(Dialog)
        self.DatosEntrada.setGeometry(QtCore.QRect(10, 20, 291, 371))
        self.DatosEntrada.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DatosEntrada.setFrameShadow(QtGui.QFrame.Raised)
        self.DatosEntrada.setObjectName("DatosEntrada")
        self.label_8 = QtGui.QLabel(self.DatosEntrada)
        self.label_8.setGeometry(QtCore.QRect(20, 190, 131, 21))
        self.label_8.setObjectName("label_8")
        self.label_2 = QtGui.QLabel(self.DatosEntrada)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label = QtGui.QLabel(self.DatosEntrada)
        self.label.setGeometry(QtCore.QRect(30, 10, 151, 21))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_6 = QtGui.QLabel(self.DatosEntrada)
        self.label_6.setGeometry(QtCore.QRect(200, 70, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtGui.QLabel(self.DatosEntrada)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtGui.QLabel(self.DatosEntrada)
        self.label_5.setGeometry(QtCore.QRect(100, 70, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtGui.QLabel(self.DatosEntrada)
        self.label_7.setGeometry(QtCore.QRect(130, 70, 16, 16))
        self.label_7.setObjectName("label_7")
        self.formulaC = QtGui.QLineEdit(self.DatosEntrada)
        self.formulaC.setGeometry(QtCore.QRect(50, 80, 16, 20))
        self.formulaC.setObjectName("formulaC")
        self.formulaS = QtGui.QLineEdit(self.DatosEntrada)
        self.formulaS.setGeometry(QtCore.QRect(150, 70, 41, 20))
        self.formulaS.setObjectName("formulaS")
        self.formulaH = QtGui.QLineEdit(self.DatosEntrada)
        self.formulaH.setGeometry(QtCore.QRect(80, 80, 16, 20))
        self.formulaH.setObjectName("formulaH")
        self.label_4 = QtGui.QLabel(self.DatosEntrada)
        self.label_4.setGeometry(QtCore.QRect(70, 70, 16, 16))
        self.label_4.setObjectName("label_4")
        self.formulaO = QtGui.QLineEdit(self.DatosEntrada)
        self.formulaO.setGeometry(QtCore.QRect(110, 80, 16, 20))
        self.formulaO.setObjectName("formulaO")
        self.label_16 = QtGui.QLabel(self.DatosEntrada)
        self.label_16.setGeometry(QtCore.QRect(30, 150, 141, 21))
        self.label_16.setObjectName("label_16")
        self.label_10 = QtGui.QLabel(self.DatosEntrada)
        self.label_10.setGeometry(QtCore.QRect(20, 230, 131, 21))
        self.label_10.setObjectName("label_10")
        self.presion1 = QtGui.QLineEdit(self.DatosEntrada)
        self.presion1.setGeometry(QtCore.QRect(90, 210, 113, 20))
        self.presion1.setObjectName("presion1")
        self.selecDatoExtra2 = QtGui.QComboBox(self.DatosEntrada)
        self.selecDatoExtra2.setGeometry(QtCore.QRect(20, 310, 141, 22))
        self.selecDatoExtra2.setObjectName("selecDatoExtra2")
        self.selecDatoExtra2.addItem("")
        self.selecDatoExtra2.addItem("")
        self.selecDatoExtra2.addItem("")
        self.selecDatoExtra2.addItem("")
        self.label_11 = QtGui.QLabel(self.DatosEntrada)
        self.label_11.setGeometry(QtCore.QRect(30, 260, 131, 21))
        self.label_11.setObjectName("label_11")
        self.datoExtra2 = QtGui.QLineEdit(self.DatosEntrada)
        self.datoExtra2.setGeometry(QtCore.QRect(170, 310, 91, 20))
        self.datoExtra2.setObjectName("datoExtra2")
        self.temperatura1 = QtGui.QLineEdit(self.DatosEntrada)
        self.temperatura1.setGeometry(QtCore.QRect(90, 230, 113, 20))
        self.temperatura1.setObjectName("temperatura1")
        self.label_9 = QtGui.QLabel(self.DatosEntrada)
        self.label_9.setGeometry(QtCore.QRect(20, 210, 131, 21))
        self.label_9.setObjectName("label_9")
        self.relacionMezcla = QtGui.QDoubleSpinBox(self.DatosEntrada)
        self.relacionMezcla.setGeometry(QtCore.QRect(150, 110, 62, 22))
        self.relacionMezcla.setMaximum(2.0)
        self.relacionMezcla.setSingleStep(0.01)
        self.relacionMezcla.setProperty("value", 1.0)
        self.relacionMezcla.setObjectName("relacionMezcla")
        self.label_12 = QtGui.QLabel(self.DatosEntrada)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 131, 21))
        self.label_12.setObjectName("label_12")
        self.calorQ = QtGui.QLineEdit(self.DatosEntrada)
        self.calorQ.setGeometry(QtCore.QRect(180, 150, 91, 20))
        self.calorQ.setObjectName("calorQ")
        self.calcular = QtGui.QPushButton(self.DatosEntrada)
        self.calcular.setGeometry(QtCore.QRect(90, 340, 101, 23))
        self.calcular.setObjectName("calcular")
        self.datoExtra1 = QtGui.QLineEdit(self.DatosEntrada)
        self.datoExtra1.setGeometry(QtCore.QRect(170, 280, 91, 20))
        self.datoExtra1.setObjectName("datoExtra1")
        self.selecDatoExtra1 = QtGui.QComboBox(self.DatosEntrada)
        self.selecDatoExtra1.setGeometry(QtCore.QRect(20, 280, 141, 22))
        self.selecDatoExtra1.setObjectName("selecDatoExtra1")
        self.selecDatoExtra1.addItem("")
        self.selecDatoExtra1.addItem("")
        self.DatosSalida = QtGui.QFrame(Dialog)
        self.DatosSalida.setGeometry(QtCore.QRect(310, 280, 361, 111))
        self.DatosSalida.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DatosSalida.setFrameShadow(QtGui.QFrame.Raised)
        self.DatosSalida.setObjectName("DatosSalida")
        self.label_17 = QtGui.QLabel(self.DatosSalida)
        self.label_17.setGeometry(QtCore.QRect(30, 40, 141, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.DatosSalida)
        self.label_18.setGeometry(QtCore.QRect(180, 78, 141, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.DatosSalida)
        self.label_19.setGeometry(QtCore.QRect(30, 60, 141, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.DatosSalida)
        self.label_20.setGeometry(QtCore.QRect(30, 80, 141, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.DatosSalida)
        self.label_21.setGeometry(QtCore.QRect(180, 58, 141, 21))
        self.label_21.setObjectName("label_21")
        self.calor2 = QtGui.QLineEdit(self.DatosSalida)
        self.calor2.setGeometry(QtCore.QRect(110, 40, 61, 20))
        self.calor2.setObjectName("calor2")
        self.label_14 = QtGui.QLabel(self.DatosSalida)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 151, 21))
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setObjectName("label_14")
        self.calorU = QtGui.QLineEdit(self.DatosSalida)
        self.calorU.setGeometry(QtCore.QRect(110, 60, 61, 20))
        self.calorU.setObjectName("calorU")
        self.trabajoW = QtGui.QLineEdit(self.DatosSalida)
        self.trabajoW.setGeometry(QtCore.QRect(110, 80, 61, 20))
        self.trabajoW.setObjectName("trabajoW")
        self.presionMedia = QtGui.QLineEdit(self.DatosSalida)
        self.presionMedia.setGeometry(QtCore.QRect(280, 58, 71, 20))
        self.presionMedia.setObjectName("presionMedia")
        self.rendimiento = QtGui.QLineEdit(self.DatosSalida)
        self.rendimiento.setGeometry(QtCore.QRect(310, 78, 41, 20))
        self.rendimiento.setObjectName("rendimiento")
        self.matrixButton = QtGui.QPushButton(self.DatosSalida)
        self.matrixButton.setGeometry(QtCore.QRect(210, 10, 131, 31))
        self.matrixButton.setObjectName("matrixButton")
        self.PlotArea = QtGui.QTabWidget(Dialog)
        self.PlotArea.setGeometry(QtCore.QRect(310, 20, 361, 251))
        self.PlotArea.setMovable(False)
        self.PlotArea.setObjectName("PlotArea")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.PlotArea.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.PlotArea.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.PlotArea.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.formulaC, self.formulaH)
        Dialog.setTabOrder(self.formulaH, self.formulaO)
        Dialog.setTabOrder(self.formulaO, self.formulaS)
        Dialog.setTabOrder(self.formulaS, self.relacionMezcla)
        Dialog.setTabOrder(self.relacionMezcla, self.calorQ)
        Dialog.setTabOrder(self.calorQ, self.presion1)
        Dialog.setTabOrder(self.presion1, self.temperatura1)
        Dialog.setTabOrder(self.temperatura1, self.selecDatoExtra2)
        Dialog.setTabOrder(self.selecDatoExtra2, self.datoExtra2)
        Dialog.setTabOrder(self.datoExtra2, self.calor2)
        Dialog.setTabOrder(self.calor2, self.calorU)
        Dialog.setTabOrder(self.calorU, self.trabajoW)
        Dialog.setTabOrder(self.trabajoW, self.presionMedia)
        Dialog.setTabOrder(self.presionMedia, self.rendimiento)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Parametros atmosféricos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Formula Química:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Datos de Entrada</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">% </span><span style=\" font-size:12pt; font-weight:600;\">S</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">C</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">O</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">+</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaC.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaS.setText(QtGui.QApplication.translate("Dialog", "00.00", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaH.setText(QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">H</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.formulaO.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Calor aportado [KJ/kg aire]=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">1</span>  [K] =</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.presion1.setText(QtGui.QApplication.translate("Dialog", "101325", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(0, QtGui.QApplication.translate("Dialog", "Alpha                            =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(1, QtGui.QApplication.translate("Dialog", "Beta                              =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(2, QtGui.QApplication.translate("Dialog", "Presion max                =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra2.setItemText(3, QtGui.QApplication.translate("Dialog", "Temp. max                  =", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Datos del ciclo:", None, QtGui.QApplication.UnicodeUTF8))
        self.datoExtra2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatura1.setText(QtGui.QApplication.translate("Dialog", "293", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>P<span style=\" vertical-align:sub;\">1</span>  [Pa] =</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Relación de mezcla F<span style=\" vertical-align:sub;\">r </span>=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.calcular.setText(QtGui.QApplication.translate("Dialog", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.datoExtra1.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra1.setItemText(0, QtGui.QApplication.translate("Dialog", "Relacion de comp.    =", None, QtGui.QApplication.UnicodeUTF8))
        self.selecDatoExtra1.setItemText(1, QtGui.QApplication.translate("Dialog", "T2                                =", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Q<span style=\" vertical-align:sub;\">2 </span>[KJ/kg aire]=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Rendimiento [KJ/kg aire]=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Qu<span style=\" vertical-align:sub;\"/>[KJ/kg aire]=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>W[KJ/kg aire]=</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Presión media [Pa]=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Datos de Salida</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.matrixButton.setText(QtGui.QApplication.translate("Dialog", "Matriz de Resultados", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotArea.setTabText(self.PlotArea.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Diagrama P-V", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotArea.setTabText(self.PlotArea.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Diagrama T-S (Mollier)", None, QtGui.QApplication.UnicodeUTF8))

